module.exports = 
	"Liner" : TWEEN.Easing.Linear.None
	"Sine.In" : Sine.easeIn
	"Quad.In" : Quad.easeIn
	"Cubic.In" : Cubic.easeIn
	"Quart.In" : Quart.easeIn
	"Quint.In" : Quint.easeIn
	"Expo.In" : Expo.easeIn
	"Circ.In" : Circ.easeIn
	"Back.In" : Back.easeIn
	"Elastic.In" : Elastic.easeIn
	"Bounce.In" : Bounce.easeIn
	"Sine.Out" : Sine.easeOut
	"Quad.Out" : Quad.easeOut
	"Cubic.Out" : Cubic.easeOut
	"Quart.Out" : Quart.easeOut
	"Quint.Out" : Quint.easeOut
	"Expo.Out" : Expo.easeOut
	"Circ.Out" : Circ.easeOut
	"Back.Out" : Back.easeOut
	"Elastic.Out" : Elastic.easeOut
	"Bounce.Out" : Bounce.easeOut
	"Sine.InOut" : Sine.easeInOut
	"Quad.InOut" : Quad.easeInOut
	"Cubic.InOut" : Cubic.easeInOut
	"Quart.InOut" : Quart.easeInOut
	"Quint.InOut" : Quint.easeInOut
	"Expo.InOut" : Expo.easeInOut
	"Circ.InOut" : Circ.easeInOut
	"Back.InOut" : Back.easeInOut
	"Elastic.InOut" : Elastic.easeInOut
	"Bounce.InOut" : Bounce.easeInOut
