// Generated by CoffeeScript 1.10.0
var Gnav,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Gnav = (function() {
  function Gnav($wrap, $trigger, $hideContents) {
    this.$wrap = $wrap;
    this.$trigger = $trigger;
    this.$hideContents = $hideContents;
    this._onScroll = bind(this._onScroll, this);
    this._onCompletedClosing = bind(this._onCompletedClosing, this);
    this._onCompletedOpening = bind(this._onCompletedOpening, this);
    this._onClickTrigger = bind(this._onClickTrigger, this);
    this.isOpen = false;
    this.wrapHeight = this.$wrap.height();
    this.scrollEvent = 'wheel mousewheel DOMMouseScroll touchmove.noScroll';
    this.scrollTop = $(window).scrollTop();
    this.duration = 100;
    this.$wrap.velocity({
      translateY: -this.wrapHeight + 30
    }, {
      duration: 0
    });
    this.$trigger.on('click', this._onClickTrigger);
    return;
  }

  Gnav.prototype._onClickTrigger = function(e) {
    $('body,html').on(this.scrollEvent, this._onScroll);
    this.$wrap.css({
      position: 'fixed'
    });
    if (this.isOpen) {
      return this._close();
    } else {
      return this._open();
    }
  };

  Gnav.prototype._open = function() {
    console.log('open');
    this.wrapHeight = this.$wrap.height();
    this.scrollTop = $(window).scrollTop();
    this.$wrap.velocity({
      translateY: -this.wrapHeight + 30
    }, {
      duration: 0
    });
    this.$wrap.show();
    this.$wrap.velocity({
      translateY: '0'
    }, {
      duration: this.duration,
      complete: this._onCompletedOpening
    });
    this.$hideContents.velocity({
      translateY: this.wrapHeight
    }, {
      duration: this.duration
    });
    return this.isOpen = true;
  };

  Gnav.prototype._onCompletedOpening = function() {
    this.$hideContents.hide();
    $('body,html').off(this.scrollEvent, this._onScroll);
    return this.$wrap.css({
      position: 'absolute'
    });
  };

  Gnav.prototype._close = function() {
    console.log('close');
    this.$hideContents.show();
    this.wrapHeight = this.$wrap.height();
    this.$wrap.velocity({
      translateY: '0'
    }, {
      duration: 0
    });
    this.$wrap.show();
    this.$wrap.css({
      position: 'fixed'
    });
    $(window).scrollTop(this.scrollTop);
    this.$wrap.velocity({
      translateY: -this.wrapHeight + 30
    }, {
      duration: this.duration,
      complete: this._onCompletedClosing
    });
    this.$hideContents.velocity({
      translateY: 0
    }, {
      duration: this.duration
    });
    return this.isOpen = false;
  };

  Gnav.prototype._onCompletedClosing = function() {
    return $('body,html').off(this.scrollEvent, this._onScroll);
  };

  Gnav.prototype._onScroll = function(e) {
    return false;
  };

  return Gnav;

})();
